safe:        true
pygments:    true
lsi:         false
markdown:    maruku
permalink:   /posts/:title
destination: public
exclude:
- CNAME
- Rakefile
- README.md
- public
- Gemfile
- Gemfile.lock
- Procfile
