# from https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false
pygments: true

# customizations
permalink:   /posts/:title
exclude:
- CNAME
- Rakefile
- README.md
- public
- Gemfile
- Gemfile.lock
- Procfile
